### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by trdwll**
add badges and move links around

### CODE REVIEW

**Comment by trdwll** [comment]
Also, instead of using your personal site for releases I recommend using github releases under https://github.com/X39/ArmA.Studio/releases

**Comment by X39** [comment]
it is planned to do that as soon as alpha status is left

however, for alpha state i want to keep the release page clean

**Comment by dedmen** [comment]
Could also make a [Github Pages](https://pages.github.com/) site.
Also after this PR the readme states that this project is MIT license. Haven't seen Arma.Studio specifying a license anywhere yet. Plus the link to the LICENSE file is a 404.

**Comment by X39** [comment]
still have to add a license
most likely that is a bug of github

**Comment by trdwll** [comment]
I don't think it's a bug of Github, but rather a shields.io bug.

**Comment by jonpas** [comment]
It's not even a bug, repository does not have a `LICENSE` (or `LICENSE.md`) file, so the links fail.

**Comment by trdwll** [comment]
@jonpas If it's not a bug then why would it return as MIT? 
Note: MIT is usually a license that is default to most things as people just want credits left intact.

**Comment by jonpas** [comment]
Because you added that shield as MIT in this PR. :p

**Comment by X39** [comment]
that problem is solved anyway now ...
project has MIT license anyway (now even with proper file in the root <3)

todo: add that note to all source files

**Comment by trdwll** [comment]
@jonpas Ohhhhhhhh "license-MIT-blue.svg". I didn't even notice it - I just pulled the shields from one of my repos.

**Pull request merged**
